### Get all
GET https://fullstackopen2023-phonebook-backend.onrender.com/api/persons

### Get by ID
GET https://fullstackopen2023-phonebook-backend.onrender.com/api/persons/1

### Create a resource
POST https://fullstackopen2023-phonebook-backend.onrender.com/api/persons
content-type: application/json

{
  "name": "Axel",
  "number": "1234567890"
}

### Delete person in phonebook
DELETE https://fullstackopen2023-phonebook-backend.onrender.com/api/persons/1
