### Get all
GET http://localhost:3001/api/persons

### Get by ID
GET http://localhost:3001/api/persons/65045a2b8934917a0b8ba917

### Create person
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Ax",
  "number": "1234567890"
}

### Update person
PUT http://localhost:3001/api/persons/6504a725fa1a1f87d7cedb0a
Content-Type: application/json

{
  "name": "a",
  "number": "045-123457"
}

### Delete person in phonebook
DELETE http://localhost:3001/api/persons/65046788e1d7f3c53c476146
