### Get all
GET http://localhost:3001/api/persons

### Get by ID
GET http://localhost:3001/api/persons/65045a2b8934917a0b8ba917

### Create person
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Axel",
  "number": "09-1234556"
}

### Update person
PUT http://localhost:3001/api/persons/650463060fa96531af373da5
Content-Type: application/json

{
  "name": "Yenn",
  "number": "022-1234556"
}

### Delete person in phonebook
DELETE http://localhost:3001/api/persons/65046788e1d7f3c53c476146
