### Get all
GET http://localhost:3001/api/persons

### Get by ID
GET http://localhost:3001/api/persons/65045a2b8934917a0b8ba917

### Create a resource
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "Axel",
  "number": "1234567890"
}

### Delete person in phonebook
DELETE http://localhost:3001/api/persons/1
